import logging
import random
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver

from langgraph_engine.state import ConfigFormState

logger = logging.getLogger("LangGraphForm")


def collect_field_node(state: ConfigFormState) -> ConfigFormState:
    """Node 1: Thu thập và cập nhật thông số Form."""
    logger.info(f"📍 [LangGraph Node: collect_field] Session '{state.get('session_id')}' | Rule: {state.get('rule_name')}")
    completed = state.get("fields_completed", [])
    if "rule_name" not in completed and state.get("rule_name"):
        completed.append("rule_name")
    if "match_pattern" not in completed and state.get("match_pattern"):
        completed.append("match_pattern")
    if "frequency" not in completed:
        completed.append("frequency")
    if "level" not in completed:
        completed.append("level")

    state["fields_completed"] = list(set(completed))
    state["status"] = "collecting"
    return state


def clarify_question_node(state: ConfigFormState) -> ConfigFormState:
    """Node 2: Xử lý câu hỏi chen ngang của Analyst mà KHÔNG làm mất State Form."""
    q_count = state.get("intervening_questions_count", 0) + 1
    state["intervening_questions_count"] = q_count
    state["status"] = "clarifying"
    logger.info(f"🔄 [LangGraph Node: clarify_question] Interruption #{q_count} | Form State Retained Intact!")
    return state


def dry_run_check_node(state: ConfigFormState) -> ConfigFormState:
    """Node 3: Chạy Sandbox Dry-Run thử nghiệm trên alert lịch sử thực tế (không bịa kết quả)."""
    logger.info(f"🧪 [LangGraph Node: dry_run_check] Running Sandbox Test for '{state.get('rule_name')}'")
    rule_id = random.randint(100100, 100999)
    pattern = state.get("match_pattern", "Failed password")
    
    draft_xml = f"""<group name="agentwazuh_custom,">
  <rule id="{rule_id}" level="{state.get('level', 12)}" frequency="{state.get('frequency', 5)}" timeframe="{state.get('timeframe', 60)}">
    <if_matched_sid>2501</if_matched_sid>
    <match>{pattern}</match>
    <description>{state.get('rule_name', 'Rule Cấu hình')} (Generated by LangGraph Engine)</description>
  </rule>
</group>"""

    # Dry-run thực tế trên alert lịch sử — tuyệt đối không chế ra `historical_matches`.
    sample_alerts = state.get("sample_alerts") or []
    from services.correlation_engine import dry_run_rule
    try:
        dry_result = dry_run_rule(draft_xml, sample_alerts)
        sandbox_res = {
            "status": "PASS",
            "tested_rule_id": rule_id,
            "historical_matches": dry_result.get("would_match_count", 0),
            "false_positive_rate": dry_result.get("estimated_false_positive_risk", "Không có dữ liệu kiểm thử"),
            "sample_matched_alert_ids": dry_result.get("sample_matched_alert_ids", [])
        }
    except Exception as e:
        logger.warning(f"⚠️ [LangGraph dry_run_check] Lỗi khi chạy dry-run: {e}")
        sandbox_res = {
            "status": "ERROR",
            "tested_rule_id": rule_id,
            "historical_matches": 0,
            "false_positive_rate": "Không chạy được do lỗi dữ liệu"
        }

    state["draft_xml"] = draft_xml
    state["sandbox_result"] = sandbox_res
    state["status"] = "sandbox_tested"
    return state


def await_human_approval_node(state: ConfigFormState) -> ConfigFormState:
    """Node 4: Điểm dừng chờ phê duyệt con người (Human-In-The-Loop Interrupt)."""
    logger.info(f"🛑 [LangGraph Node: await_human_approval] Awaiting Analyst Click Approval...")
    state["awaiting_approval"] = True
    state["status"] = "awaiting_approval"
    return state


def apply_config_node(state: ConfigFormState) -> ConfigFormState:
    """Node 5: Áp dụng cấu hình chính thức sau khi con người phê duyệt."""
    logger.info(f"✅ [LangGraph Node: apply_config] Applying Rule XML to Pending Area...")
    state["awaiting_approval"] = False
    state["status"] = "applied"
    return state


def build_config_form_graph():
    """Xây dựng StateGraph cho LangGraph Form Engine."""
    builder = StateGraph(ConfigFormState)

    builder.add_node("collect_field", collect_field_node)
    builder.add_node("clarify_question", clarify_question_node)
    builder.add_node("dry_run_check", dry_run_check_node)
    builder.add_node("await_human_approval", await_human_approval_node)
    builder.add_node("apply_config", apply_config_node)

    builder.add_edge(START, "collect_field")
    builder.add_edge("collect_field", "dry_run_check")
    builder.add_edge("dry_run_check", "await_human_approval")
    builder.add_edge("await_human_approval", END)

    memory = MemorySaver()
    graph = builder.compile(checkpointer=memory)
    return graph


# Singleton Graph Instance
config_form_graph = build_config_form_graph()
